# Generated by Django 2.0.6 on 2018-10-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180825_1642'),
        ('games', '0005_auto_20180922_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='played_sessions', to='profiles.Profile'),
        ),
    ]
