name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '10.15.1'

      - run: npm install

      - run: npm run build_prod
        env:
          CI: ""

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: "build/*"

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: "build"

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          source: "build/*"
          target: "~/build/"
