name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '10.15.1'

      - run: npm install

      - run: npm run build_prod
        env:
          CI: ""

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: "build/*"

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: "build"

      - uses: appleboy/scp-action@v0.1.7
        env:
          HOST: ${{ secrets.HOST }}
          KEY: ${{ secrets.KEY }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
        with:
          source: "build/*"
          target: "~/build/"
